- code/productivity/qvm-cmds-bash-autocomplete.sh
- code/productivity/qvm-cmds-bash-completion.sh
reworked script from https://www.mail-archive.com/qubes-users@googlegroups.com/msg20088.html:
- only one function instead of several identical ones
- fix 'grep' to match only the VM status (between '|')
> add bash autocompletion script

- docs/misc/iaq.md
Thanks to mossy's post https://www.mail-archive.com/qubes-users@googlegroups.com/msg21995.html
> add updatevm tags and steps for whonix-14

- docs/misc/iaq.md
> reorganize into sections

- docs/misc/iaq.md
documented stuff I found out while trying to setup auto-shutdown in named dispVMs.
> iaq: add process flow when opening a link/file in another VM

- code/README.md
> add link to qubes-split-dm-crypt

- code/README.md
add link to unman's ubuntu repo
reword the link to zrubi's blog
> add link to unman's ubuntu repo

- docs/customization/windows-gaming-hvm.md
> File for #61

- docs/README.md
> add qvm-create-windows-qube link

- docs/README.md
- docs/customization/terminal-defaults.md
- docs/system/vm-console.md
> Add files in as per #73.

- docs/README.md
- docs/system/vm-console.md
Describe both `qvm-console-dispvm` and `xl console`
> add documentation for accessing VM console

- docs/README.md
- docs/system/backup-reminders.md
Add documentation for creating pop-up notifications when it's been more than N days since a backup.
> Backup reminder script

- docs/README.md
- docs/system/vm-image.md
(title should be self-explanatory)
> Add instructions for mounting a VM's private storage in another VM

- code/OS-administration/build-archlinux.sh
- code/README.md
Script to build the archlinux minimal template. 
Contains some comment about where to add custom version of QubesOS repository, and indications to create a archlinux repository for qubes os packages
> add archlinux building script

- docs/common-tasks/opening-urls-in-vms.md
Possible typo or changed after the fact.
> Add `\policy` to RPC directories

- docs/README.md
Link to someone old blog post, but also work on QubesOS 4.0
> Create a pihole qube

- code/README.md
> added my stuff (3hhh)

- docs/configuration/zoom_dispvm.md
see https://github.com/QubesOS/qubes-doc/pull/1000
> Document Running Zoom in a DispVM

- docs/README.md
- docs/customization/screenlockers.md
Should make it easier to address https://github.com/QubesOS/qubes-issues/issues/1917
> Custom screenlocker guide

- docs/README.md
- docs/wireguard/README.md
See https://github.com/QubesOS/qubes-issues/issues/6161
> Add wireguard guide

- docs/customization/screenlockers.md
added a note as I experienced it not to be reliable
> xss-lock security note

- docs/configuration/network-printer.md
The package is no longer installed in the default template vm
> Printer settings: Install instructions.

- docs/os/pentesting.md
instructions maintained by Parrot
> adding official Parrot installation instructions

- docs/configuration/screen-share.md
https://github.com/QubesOS/qubes-issues/issues/6426
> added Screen Sharing Page

- docs/misc/qubes-evaluation-walkthrough.md
This is the start of a evaluation walkthrough.  I'd like to get feedback to make sure you guys are going to allow this topic to be added to the repo before I work on it any more.  (I'm expecting a "that's a horrible idea"  kind of reaction from some people).
> Started a evaluation walkthrough

- code/productivity/qvm-copy-to-dom0.sh
Fix multiple issues with filenames containing spaces and starting dashes.
The result is not tested by me at all, please check the changes before use.
> Fix multiple issues in qvm-copy-to-dom0.sh

- docs/configuration/vpn.md
I have done this change on my setup to fix the random disconnection I am facing.
If the VPN go down, wait and reconnect to the vpn
* add 5 second delay
* call /rw/config/rc.local script
> Auto reconnect VPN if disconnected

- docs/building/building-archlinux-template.md
Improve wording, change from "Nor ... nor" form to "Neither ... nor"
(Unless a more conversational tone is desired in the writing.)
> Improve Wording

- docs/os/pentesting.md
New link to parrot install in qubes os.
> Updated link

- docs/common-tasks/setup-trezor-cryptocurrency-hardware-wallet.md
Add a quick cheat sheet to answer the commonly asked question, "how do I setup Trezor on my Qubes machine?"
The current documentation is rather confusing and spread over both the Trezor and Whonix wiki pages.
> add Trezor setup cheat-sheet

- docs/configuration/vpn.md
This fixes the notifications timeout issue at first boot but have not tested any further (what happens if no connection etc).
> Move notifications after vpn initialization

- docs/README.md
- docs/customization/windows-gaming-hvm.md
Mostly adding IOMMU informations, and R4.1 ram patch information. 
The amount of changes in this commit is because I generated the markdown from latex using pandoc.
> Update Windows Gaming HVM documentation

- docs/configuration/disk-trim.md
Each VM should launch the trim command.
By the [dum0 forum user](https://forum.qubes-os.org/t/trim-in-qubes-os/4414/6)
> disk-trim: in each VM

- docs/customization/dpi-scaling.md
Add notes to fix issues in GTK3 applications and a minor note about i3 wm.
> DPI scaling

- docs/privacy/signal.md
Use the newer apt throughout, instead of the older apt-get
> Use apt instead of apt-get

- docs/os/windows/windows-tools41.md
The added pictures QWT_install_select.png, QWT_install_driver.png, and QWT_install_no_restart.png probably have to be moved to /attachment/wiki/WindowsAppVms/, and the links correspondingly updated. But this would need access rights that I do not possess.
> Add some screenshots of installation

- docs/os/windows/windows-vm41.md
I have tested and confirmed Windows 8.1 working well in an HVM. QWT work fine too straight up after the system installation - there's even no need to install updates.
I dropped some information on this. Also, there was a mention of Windows XP being installable but it's better if one knows, that QWT don't work on XP.
> Clarify info on supported Windows Versions

- docs/os/windows/windows-vm41.md
After a bit of tinkering I finally managed to make USB devices work in a Windows 7 qube. I'm sharing what procedure worked for me and on which configuration it did.
Relevant forum thread: https://forum.qubes-os.org/t/qwt-installed-but-no-usb-or-file-copy-in-windows-qube/13912/12
> Troubleshooting invisible USB devices in Windows 7

- docs/README.md
- docs/configuration/bluetooth.md
A very quick one - a simple installation of one package.
Still appropriate to write about it since people were asking - [relevant forum thread](https://forum.qubes-os.org/t/why-the-system-is-more-favorable-to-malicious-attackers-and-not-users/14301/15).
> Blueman installation

- docs/misc/iaq.adoc
Cleaned up the file docs/misc/iaq.adoc a bit.
> Infrequently Asked Questions - a lot of changes

- docs/privacy/signal.md
* Use teletype for possible arguments of command
* Remove extra spaces
* Use more concise wording
* Other grammar fixes
> Make minor edits in signal.md

- docs/privacy/anonymizing-your-mac-address.md
* Use consistent sentence case of titles
* As done in official Qubes OS documentation
* Fix spelling of Wi-Fi
* Use 3 periods for ellipsis
* Edit a few word choices/ordering
* Use "drop-down list"
> Make minor edits in anonymizing-your-mac-address.md

- docs/privacy/anonymizing-your-mac-address.md
Mostly based on discussions with @feffiboujike on the [forum](https://forum.qubes-os.org/t/anonymizing-mac-address-documentation-clarification/14731).
References #217
> anonymize MAC & hostname: misc fixes

- docs/privacy/anonymizing-your-mac-address.md
cf. https://forum.qubes-os.org/t/anonymizing-mac-address-documentation-clarification/14731
> anonymize MAC: misc fixes

- docs/security/multifactor-authentication.md
A short guide on how to use zbar & pass-otp as an alternative to oathtool
> zbar & pass-otp

- docs/troubleshooting/intel-igfx-troubleshooting.md
Following up # [4782](https://github.com/QubesOS/qubes-issues/issues/4782), [7507](https://github.com/QubesOS/qubes-issues/issues/7507), [7664](https://github.com/QubesOS/qubes-issues/issues/7664), [7902](https://github.com/QubesOS/qubes-issues/issues/7902), [7894](https://github.com/QubesOS/qubes-issues/issues/7894). Forum [post](https://forum.qubes-os.org/t/i3-not-working-properly-video-graphic-issues/6365), [post](https://forum.qubes-os.org/t/qubesos-freeze-crash-and-reboots/12851/172). Blog [post](https://danten.io/qubes-os-4-1-i3-blurred-graphics-on-t450s-fix/)
ping @awokd and @andrewdavidwong (policy of not merging oneself's PRs).
> Reformat intel fgx troubleshooting doc and add section about tearing

- docs/troubleshooting/intel-igfx-troubleshooting.md
> Add mention about disabling PSR to fix tearing

- docs/os/windows/windows-tools41.md
After a lot of try and error I stumbled over this. (I found the error logs on C:\) Better solution would probably be a check during install, but that´s out of my scope.
> clarified need to assign specific drive letter

- docs/customization/tailscale.md
Provides a quick tutorial for configuring persistent Tailscale tunnel in a designated AppVM.
> Create Tailscale how-to

- docs/os/windows/windows-tools41.md
Modified the order of flag and vmname arguments. According to `man qvm-start` it is the proper way for it. I checked that command still works, of course.
> Update windows-tools41.md - Modified the order of flag and vmname arguments

- README.md
> Shadow qube add

- README.md
Some users may be lost if they are linked to the forum.
> Link directly to the guides category
