docs/qubes-doc-folders.txt

Suggestion for a folder, qubes-projects, which allows sub-folders with more individual freedom on content-structure, for as long it is kept inside this single sub-folder for every project. It also makes it easier to find all Qubes projects in a single location, whether briefly documented, or extensively documented, keeping them all together makes it easier to navigate. For example Qubes-TV may have a couple of different documents here, or Qubes-Binary-Router documentations. Projects like these and other projects that people may put up, or found elsewhere on the internet, could fit neatly in such a specialized folder. Thoughts on this? 
Examples
- /contents/docs/qubes-projects/qubes-tv/broader-content-structure-freedom.
- /contents/docs/qubes-projects/qubes-binary-router/broader-content-str …

thoughts on a Qubes-projects folder

---

docs/configuration/qmenu.md

Add a short guide on how to install [qmenu](https://github.com/sine3o14nnae/qmenu) in dom0 to use dmenu for managing Qubes specific tasks.The installation itself has serious security implications but users with issues like [#3910](https://github.com/QubesOS/qubes-issues/issues/3910), [#4294](https://github.com/QubesOS/qubes-issues/issues/4294), [#5037](https://github.com/QubesOS/qubes-issues/issues/5037), [#5386](https://github.com/QubesOS/qubes-issues/issues/5386) & [#5447](https://github.com/QubesOS/qubes-issues/issues/5447) could benifit from these tools.

add guide on how to install qmenu

---

code/README.md

* do-snapshot.py have been marked as obsolete by its author, removing the link
* updating the qvm-portfwd-iptables link to the latest version, forked by fepitre (https://gist.github.com/Joeviocoe/6c4dc0c283f6d6c5b1a3f5af8793292b#gistcomment-3118596)
* adding a new section about prolific author (aka: tasket create and maintain a lot of usefull scripts in his repo, adding a direct link to his profile to check for new scripts/idea )

Refresh part of the code Readme

---

docs/wireguard/README.md

Some sites work in sys-wireguard, but did not work in an AppVM
connected to sys-wireguard. Examples:
https://duckduckgo.com
https://atlassian.net
The problem is caused by MTU. The solution was proposed on
https://github.com/QubesOS/qubes-issues/issues/5264#issuecomment-707683771

WireGuard guide: fix MTU issue

---

docs/building/building-archlinux-template.md

Add troubleshooting documentation for missing pulsecore headers error during gui-agent-linux compilation.

add troubleshooting for missing pulsecore error

---

docs/configuration/split-ssh.md

See https://www.qubes-os.org/doc/qrexec/#policy-files for more info.
Correct me if I'm wrong, but I'm pretty sure that those directories were wrong. :)

Added the missing policy/ directory in the dom0 setup description for Split SSH

---

docs/configuration/screen-share.md

So sorry, looked over the documentation guidelines again and realized variable names should have underscores as separators not dashes.

Conforming to style guidelines

---

docs/README.md
docs/mumble/README.md

To secure communications over Mumble, you should control the machine on which
the Mumble server is running. You can run the server locally and expose it
to the world through VPS using wireguard.
Here is my guide on how to do it.

Add guide on exposing Mumble server running locally in Qubes through VPS

---

docs/os/pentesting/kali.md

This pull request adds documentation for fixing the Qubes PulseAudio configuration (audio and microphone) after being broken as a result of installing the `kali-defaults` package in Kali Linux.
The `kali-defaults` package is a very common package installed by many [Kali Linux metapackages](https://tools.kali.org/kali-metapackages) (including `kali-linux-core`). Here is the description provided by the package:
```
This package implements various default settings within Kali.
The size of this package (including its dependencies) should be rather limited
because it is included in all Kali images, even minimalistic ones such as
docker images.
```

Fix Qubes PulseAudio (Audio and Microphone) in Kali Linux

---

code/productivity/qvm-copy-to-vm2.sh

Fix multiple issues with filenames containing spaces and starting dashes.
The result is not tested by me at all, please check the changes before use.

Fix multiple issues in qvm-copy-to-vm2.sh

---

docs/os/pentesting/kali.md

hkps://keys.gnupg.net does not resolve any longer. Kali official docs recommend hkps://keys.openpgp.org
source: https://www.kali.org/docs/introduction/download-official-kali-linux-images/

Update instructions for Kali install

---

docs/configuration/split-ssh.md

This first fixes a couple of documentation issues encountered while configuring, and then makes sure the user gets a confirmation dialog when a key gets used (when using plain ssh-agent).
Note we should probably also enhance the KeepassXC tutorial to use the similar option it provides.

Split-ssh fixes and notification enabling

---

docs/building/building-archlinux-template.md

1. The recommendation for fedora-33 was dropped. I tried fedora-33-minimal on 4.1rc3 and it failed with some obscure error that didn't occur on fedora-34. Works better than 33-min and saves the user a bit of disk space. So I see no need for this recommendation.
2. Deleted the `effective uid is not 0` part, fixed by https://github.com/marmarek/qubes-builder/commit/c209be5e4a3cafae882bea4e438e48552805ee52
3. Added some helpful info about the xenstore-bug from this issue: https://github.com/QubesOS/qubes-issues/issues/7098. Validated the workaround myself.

Deleted some outdated info in the guide, adding some important stuff

---

docs/configuration/split-ssh.md

I have tested those changes on Debian 11. Split SSH still works with them.

refactor: Fix ShellCheck warnings in /etc/qubes-rpc/qubes.SshAgent

---

docs/privacy/signal.md

According to the Qubes forum [^1][^2][^3][^4] some people had problems so i think this update can help. Thanks to pr0xy and Sven.
[^1]: https://forum.qubes-os.org/t/signal-desktop-how-to-install-for-use-in-multiple-app-vms/5221
[^2]: https://forum.qubes-os.org/t/debian-10-minimal-configuration/2603/70
[^3]: https://forum.qubes-os.org/t/apt-key-is-depreciated/8184/5
[^4]: https://forum.qubes-os.org/t/issues-installing-signal-with-qubes-4-1-bullseye-instead-of-xenial-in-main/8453/8

Update for Qubes 4.1 and Debian 11

---

docs/privacy/signal.md

* Change URL from Open Whisper Systems site to Signal's site (the former always redirects to the latter anyways)
* Delete mention of checking if two words match during 1-on-1 Signal calls in block quote (I haven't seen this on Signal mobile since at least October 2020, when group calls came to desktop & iPad)
* Update info on Signal being developed/supported by Signal Foundation and Signal Messenger LLC, which have superseded Open Whisper Systems after 2018
* Add distinction of FOSS license between mobile clients and desktop client+server
* State clearly that Signal Desktop will be installed on Qubes OS
* Add reference to official Linux instructions from Signal
* Move clarifying notes in Step 3 commands to Bash comments at end of file, to better simulate terminal emulator standard output …

Update Wikipedia info & polish style in signal.md

---

docs/os/windows/windows-tools.md
docs/os/windows/windows-vm.md

Some of the information in the windows docs is outdated given the recent work on QWT and the recent 4.1 release. Following a [discussion in this post](https://forum.qubes-os.org/t/wip-windows-qwt-user-reports/9687) and a few forum posts showing that people were confused with the current instructions, it seems helpful to direct users to more up-to-date documentation (albeit "telegraphic") until somebody updates the current docs - which might take a bit of time.
Note: an alternative is to dismiss this PR and add a link to the forum wiki post in the [official doc](https://www.qubes-os.org/doc/windows/)

add link to forum wiki / crowdsourcing user experience

---

docs/privacy/signal.md

Bullseye because the rest of the document discusses Debian 11.
Also make "Signal" case consistent throughout.

signal.md: Change example Debian repo to bullseye

---

docs/privacy/signal.md

Hi,
PR  #186 changed the signal repo to `bullseye` but Signal don't deliver release there, user adding this repository will get the following message:
```
E: The repository 'https://updates.signal.org/desktop/apt bullseye Release' does not have a Release file.
```
Xenial is the only repo working for now, so I edited it back and added a little explanation above it.

Fix Signal repo + add reason for xenial repo

---

docs/privacy/anonymizing-your-mac-address.md

In order to avoid leaking the MAC in IPv6.

set ipv6.ip6-privacy=2

---

docs/building/building-archlinux-template.md

The archlinux building guide had a lot of different format types and
styles of writing which make it harder to read than necessary.
Furthermore, some information was added that is of no special interest
there.
This commit tries to use a consistent and simple style for formatting
the content and uses wordings that tells the reader what to do.

Update arch building guide to be more concise

---

docs/customization/language-localization.md

Additional note: The description for enabling UTF-8 in the linked document is outdated; it refers to a file that is ignored since R4.0 and replaced by the `qvm-features` command.

Describe language selection for dom0 and Templates

---

docs/os/centos.md

With the end of 2021, CentOS ended its life in its stable form. This instruction is about where to look out to replicate the CentOS experience with other RHEL replicas (AlmaLinux, EuroLinux, Rocky Linux).

The solution for CentOS 8 End Of Life

---

docs/os/centos.md

Recently [I have created a guide, how to migrate CentOS to its successors](https://github.com/Qubes-Community/Contents/pull/214).
Turns out, this guide was wrong. I already did some tweaks rather than start from a fresh template. This time I wrote a guide that applies to the fresh template with CentOS 8.2.
Still, I'd be grateful if someone else could double-check me to be 100% sure the earlier mistake will never happen again.

Fixes for CentOS 8.2 template

---

docs/privacy/anonymizing-your-mac-address.md

cf.
https://forum.qubes-os.org/t/anonymizing-mac-address-documentation-clarification/14731

anonymize MAC: re-introduce ipv6.dhcp-duid=stable-uuid

---

docs/configuration/split-ssh.md

As per [this](https://cirosantilli.com/markdown-style-guide/#dollar-signs-in-shell-code) (somewhat authoritative?) Markdown Style Guide commands that can be copy-pasted should not be prefixed by a prompt.

Remove prompt from commands that can be copied

---

docs/customization/dpi-scaling.md

Most Qubes-native applications don't scale well in dom0 because they are made in Qt.

Add QT Scaling to dpi-scaling.md
